# Generated by Django 6.0.3 on 2026-04-05 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('valide_par_chef', models.BooleanField(default=False)),
                ('valide_par_directeur', models.BooleanField(default=False)),
                ('taux_plagiat', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='soumis', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
