# Generated by Django 6.0.3 on 2026-04-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='commentaire_validation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
