# Generated by Django 4.2.30 on 2026-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_commentaire_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
    ]
