# Generated by Django 6.0.4 on 2026-04-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_alter_theme_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide_chef', 'Validé par le Chef'), ('rejete_chef', 'Rejeté par le Chef'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
    ]
