# Generated by Django 6.0.3 on 2026-04-08 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='bibliotheque/')),
                ('type', models.CharField(choices=[('theme', 'Thème'), ('memoire', 'Mémoire')], max_length=20)),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_ajoutees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
