# Generated by Django 6.0.4 on 2026-04-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='ressource_liee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lie_a', to='bibliotheque.ressource'),
        ),
    ]
