# Generated by Django 6.0.3 on 2026-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_commentaire_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide_chef', 'Validé par le Chef'), ('rejete_chef', 'Rejeté par le Chef'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
    ]
