# Generated by Django 6.0.3 on 2026-04-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_statut'),
        ('themes', '0002_theme_commentaire_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='theme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='themes.theme'),
        ),
    ]
