# Generated by Django 6.0.3 on 2026-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('chef', 'Chef Departement'), ('directeur', 'Directeur Adjoint')], default='etudiant', max_length=20),
        ),
    ]
