# Generated by Django 6.0.3 on 2026-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_nom_user_prenom_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ine',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
