# Generated by Django 4.2.30 on 2026-04-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0002_testplagiattheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
